In [2]:
import pandas as pd

In [5]:
df=pd.read_csv(R"C:\Users\abdul\3D Objects\Python Work\sales.csv")

In [ ]:
df

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

In [6]:
print(df.head(8))

   order_id        date region  product     category customer_type  quantity  \
0         1  2024-04-12   East   Laptop  Electronics     Returning         8
1         2  2024-12-14  South  Monitor  Accessories     Returning         2
2         3  2024-09-27  North    Phone  Accessories           New         5
3         4  2024-04-16   West    Mouse  Electronics     Returning         1
4         5  2024-03-12   West    Phone  Electronics     Returning         7
5         6  2024-07-07   West   Laptop  Electronics           New         8
6         7  2024-01-21   East    Mouse  Accessories     Returning         6
7         8  2024-04-12   West    Phone  Accessories     Returning         5

   price  discount     sales
0    590      0.09   4295.20
1    262      0.18    429.68
2    512      0.09   2329.60
3    485      0.09    441.35
4    332      0.22   1812.72
5   1480      0.01  11721.60
6    137      0.27    600.06
7   1117      0.26   4132.90

In [ ]:
print(df.info())

In [ ]:
print(df.columns)

In [8]:
df.rename(columns={
    "order_id": "OrderID"
}, inplace=True)
df

,OrderID,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

In [9]:
print(df.isnull().sum())

OrderID          0
date             0
region           0
product          0
category         0
customer_type    0
quantity         0
price            0
discount         0
sales            0
dtype: int64

In [10]:
print(df.duplicated().sum())

0

In [11]:
df['date'] = pd.to_datetime(df['date'])
print(df.dtypes)

OrderID                   int64
date             datetime64[us]
region                      str
product                     str
category                    str
customer_type               str
quantity                  int64
price                     int64
discount                float64
sales                   float64
dtype: object

In [13]:
df['price'] = df['price'].astype(float)
print(df['price'].dtype)

float64

In [14]:
df['region'] = df['region'].str.strip().str.title()
print(df['region'])

0       East
1      South
2      North
3       West
4       West
       ...
495    South
496    North
497    South
498    North
499    North
Name: region, Length: 500, dtype: str

In [15]:
# Total sales by region
total_sales = df.groupby("region")["sales"].sum()
print("Total Sales by Region:\n", total_sales)

# Region with highest sales
highest_region = total_sales.idxmax()
print("\nRegion with highest sales:", highest_region)

Total Sales by Region:
 region
East     422023.71
North    509052.69
South    362158.72
West     373294.66
Name: sales, dtype: float64

Region with highest sales: North

In [17]:
df.groupby("product")["discount"].mean()

product
Keyboard    0.147436
Laptop      0.141149
Monitor     0.147733
Mouse       0.153021
Phone       0.155125
Tablet      0.135357
Name: discount, dtype: float64

In [19]:
df.groupby("product")["quantity"].sum().sort_values(ascending=False).head(5)

product
Mouse       481
Laptop      449
Tablet      411
Keyboard    390
Phone       383
Name: quantity, dtype: int64

In [20]:
df['month'] = df['date'].dt.month

# Calculate total sales per month
monthly_sales = df.groupby("month")["sales"].sum()
print("Monthly Sales Trend:\n", monthly_sales)

Monthly Sales Trend:
 month
1      98673.77
2     131625.24
3      70335.46
4     150967.04
5     176939.29
6     155607.27
7     128419.96
8     194347.39
9     157999.69
10    131809.83
11    118704.40
12    151100.44
Name: sales, dtype: float64

In [22]:
avg_with_discount = df[df['discount'] > 0]["sales"].mean()

avg_without_discount = df[df['discount'] == 0]["sales"].mean()

print("Average Sales with Discount:", avg_with_discount)
print("Average Sales without Discount:", avg_without_discount)

Average Sales with Discount: 3310.8291170431207
Average Sales without Discount: 4165.846153846154

In [24]:
df.groupby("product")["sales"].sum().idxmax()

'Laptop'

In [25]:
# Total sales by customer type
total_sales_customer = df.groupby("customer_type")["sales"].sum()
print("Total Sales by Customer Type:\n", total_sales_customer)

# Average sales per order by customer type
avg_sales_customer = df.groupby("customer_type")["sales"].mean()
print("\nAverage Sales per Order by Customer Type:\n", avg_sales_customer)

# Count of orders by customer type
order_count = df.groupby("customer_type")["OrderID"].count()
print("\nNumber of Orders by Customer Type:\n", order_count)

Total Sales by Customer Type:
 customer_type
New          793937.36
Returning    872592.42
Name: sales, dtype: float64

Average Sales per Order by Customer Type:
 customer_type
New          3321.913640
Returning    3343.265977
Name: sales, dtype: float64

Number of Orders by Customer Type:
 customer_type
New          239
Returning    261
Name: OrderID, dtype: int64